//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAsyncOld.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.ILiczbyPierwsze")]
    public interface ILiczbyPierwsze {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiczbyPierwsze/GetPierwsze", ReplyAction="http://tempuri.org/ILiczbyPierwsze/GetPierwszeResponse")]
        int[] GetPierwsze(int rangeA, int rangeB);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILiczbyPierwsze/GetPierwsze", ReplyAction="http://tempuri.org/ILiczbyPierwsze/GetPierwszeResponse")]
        System.IAsyncResult BeginGetPierwsze(int rangeA, int rangeB, System.AsyncCallback callback, object asyncState);
        
        int[] EndGetPierwsze(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILiczbyPierwszeChannel : ClientAsyncOld.ServiceRef.ILiczbyPierwsze, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPierwszeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPierwszeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiczbyPierwszeClient : System.ServiceModel.ClientBase<ClientAsyncOld.ServiceRef.ILiczbyPierwsze>, ClientAsyncOld.ServiceRef.ILiczbyPierwsze {
        
        private BeginOperationDelegate onBeginGetPierwszeDelegate;
        
        private EndOperationDelegate onEndGetPierwszeDelegate;
        
        private System.Threading.SendOrPostCallback onGetPierwszeCompletedDelegate;
        
        public LiczbyPierwszeClient() {
        }
        
        public LiczbyPierwszeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiczbyPierwszeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiczbyPierwszeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiczbyPierwszeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetPierwszeCompletedEventArgs> GetPierwszeCompleted;
        
        public int[] GetPierwsze(int rangeA, int rangeB) {
            return base.Channel.GetPierwsze(rangeA, rangeB);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPierwsze(int rangeA, int rangeB, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPierwsze(rangeA, rangeB, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int[] EndGetPierwsze(System.IAsyncResult result) {
            return base.Channel.EndGetPierwsze(result);
        }
        
        private System.IAsyncResult OnBeginGetPierwsze(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int rangeA = ((int)(inValues[0]));
            int rangeB = ((int)(inValues[1]));
            return this.BeginGetPierwsze(rangeA, rangeB, callback, asyncState);
        }
        
        private object[] OnEndGetPierwsze(System.IAsyncResult result) {
            int[] retVal = this.EndGetPierwsze(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPierwszeCompleted(object state) {
            if ((this.GetPierwszeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPierwszeCompleted(this, new GetPierwszeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPierwszeAsync(int rangeA, int rangeB) {
            this.GetPierwszeAsync(rangeA, rangeB, null);
        }
        
        public void GetPierwszeAsync(int rangeA, int rangeB, object userState) {
            if ((this.onBeginGetPierwszeDelegate == null)) {
                this.onBeginGetPierwszeDelegate = new BeginOperationDelegate(this.OnBeginGetPierwsze);
            }
            if ((this.onEndGetPierwszeDelegate == null)) {
                this.onEndGetPierwszeDelegate = new EndOperationDelegate(this.OnEndGetPierwsze);
            }
            if ((this.onGetPierwszeCompletedDelegate == null)) {
                this.onGetPierwszeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPierwszeCompleted);
            }
            base.InvokeAsync(this.onBeginGetPierwszeDelegate, new object[] {
                        rangeA,
                        rangeB}, this.onEndGetPierwszeDelegate, this.onGetPierwszeCompletedDelegate, userState);
        }
    }
}
